name: Build

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@main
      - uses: mlugg/setup-zig@v2
        with:
          version: master
      - name: C/C++
        run: |
          mkdir build
          cd build
          cmake ..
          cmake --build .
      - name: Zig
        run: |
          zig build --verbose
